apiVersion: v1
kind: Service
metadata:
  name: {{ Release.Name }}-svc
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: simple-app
  type: NodePort