---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    dest_file: /var/www/html


  tasks:
  - name: Chack and print Linux OS
    debug: var=ansible_os_family


  - block: #=======Block for RedHat=======

      - name: Install Apache Web Server
        yum: name=httpd state=latest

      - name: Copy MyHomePage to Servers
        copy: src={{ source_file }} dest={{ dest_file }}
        notify: Restart Apache RedHat

      - name: Start WebServer and make it enable on boot
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"


  - block: #=======Block for Debian=======

      - name: Install Apache Web Server
        yum: name=apache2 state=latest

      - name: Copy MyHomePage to Servers
        copy: src={{ source_file }} dest={{ dest_file }}
        notify: Restart Apache Debian

      - name: Start WebServer and make it enable on boot
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted